# Generated by Django 3.1.7 on 2021-05-13 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre_id', models.AutoField(primary_key=True, serialize=False)),
                ('genre_value', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Genre',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(db_column='group_name', max_length=100)),
            ],
            options={
                'db_table': 'Group',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.IntegerField(primary_key=True, serialize=False)),
                ('movie_title', models.CharField(max_length=500)),
                ('release_year', models.IntegerField()),
                ('image_url', models.CharField(max_length=250, null=True)),
                ('description_en', models.CharField(max_length=1000, null=True)),
                ('description_ro', models.CharField(max_length=1500, null=True)),
            ],
            options={
                'db_table': 'Movie',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='username', max_length=100)),
                ('password', models.CharField(db_column='password', max_length=100)),
                ('profile_image', models.ImageField(default=None, null=True, upload_to='')),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='GroupUserMovie',
            fields=[
                ('group_movie_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_id', models.ForeignKey(db_column='group_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='filmdb.group')),
                ('movie_id', models.ForeignKey(db_column='movie_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='filmdb.movie')),
            ],
            options={
                'db_table': 'GroupMovie',
            },
        ),
        migrations.CreateModel(
            name='GroupUser',
            fields=[
                ('group_user_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_id', models.ForeignKey(db_column='group_id', on_delete=django.db.models.deletion.CASCADE, to='filmdb.group')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='filmdb.user')),
            ],
            options={
                'db_table': 'GroupUser',
            },
        ),
        migrations.CreateModel(
            name='TrainData',
            fields=[
                ('rating_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('rating', models.FloatField()),
                ('movie_id', models.ForeignKey(db_column='movie_id', on_delete=django.db.models.deletion.CASCADE, to='filmdb.movie')),
            ],
            options={
                'db_table': 'TrainData',
                'unique_together': {('movie_id', 'user_id')},
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('rating_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.FloatField()),
                ('movie_id', models.ForeignKey(db_column='movie_id', on_delete=django.db.models.deletion.CASCADE, to='filmdb.movie')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='filmdb.user')),
            ],
            options={
                'db_table': 'Rating',
                'unique_together': {('movie_id', 'user_id')},
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('prediction_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('rating', models.FloatField()),
                ('movie_id', models.ForeignKey(db_column='movie_id', on_delete=django.db.models.deletion.CASCADE, to='filmdb.movie')),
            ],
            options={
                'db_table': 'Prediction',
                'unique_together': {('movie_id', 'user_id')},
            },
        ),
        migrations.CreateModel(
            name='MovieGenre',
            fields=[
                ('movie_genre_id', models.AutoField(primary_key=True, serialize=False)),
                ('genre_id', models.ForeignKey(db_column='genre_id', on_delete=django.db.models.deletion.CASCADE, to='filmdb.genre')),
                ('movie_id', models.ForeignKey(db_column='movie_id', on_delete=django.db.models.deletion.CASCADE, to='filmdb.movie')),
            ],
            options={
                'db_table': 'MovieGenre',
                'unique_together': {('movie_id', 'genre_id')},
            },
        ),
    ]
