# Generated by Django 3.1.7 on 2021-04-06 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filmdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingMovieUser',
            fields=[
                ('rating_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.FloatField()),
                ('movie_id', models.ForeignKey(db_column='movie_id', on_delete=django.db.models.deletion.CASCADE, to='filmdb.movie')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='filmdb.user')),
            ],
            options={
                'db_table': 'RatingUserMovie',
                'unique_together': {('movie_id', 'user_id')},
            },
        ),
    ]
