# Generated by Django 3.1.7 on 2021-05-16 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filmdb', '0002_auto_20210516_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviegenre',
            name='movie_id',
            field=models.ForeignKey(db_column='movie_id', on_delete=django.db.models.deletion.CASCADE, related_name='movie_id_movie_genre', to='filmdb.movie'),
        ),
    ]
