# Generated by Django 3.1.7 on 2021-04-17 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmdb', '0002_auto_20210415_2203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='description',
            new_name='description_en',
        ),
    ]
