# Generated by Django 3.1.7 on 2021-03-28 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filmdb', '0002_auto_20210306_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.CreateModel(
            name='TrainData',
            fields=[
                ('rating_id', models.AutoField(primary_key=True, serialize=False)),
                ('movie_id', models.ForeignKey(db_column='movie_id', on_delete=django.db.models.deletion.CASCADE, to='filmdb.movie')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='filmdb.user')),
            ],
            options={
                'db_table': 'TrainData',
                'unique_together': {('movie_id', 'user_id')},
            },
        ),
    ]
