# Generated by Django 3.1.7 on 2021-05-16 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmdb', '0003_auto_20210516_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.FloatField(null=True),
        ),
    ]
