# Generated by Django 3.1.7 on 2021-03-28 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmdb', '0003_auto_20210328_1943'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='traindata',
            table='traindata',
        ),
    ]
