# Generated by Django 3.1.7 on 2021-04-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmdb', '0004_movie_description_ro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='description_ro',
            field=models.CharField(max_length=1500, null=True),
        ),
    ]
