# Generated by Django 3.1.7 on 2021-03-28 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmdb', '0004_auto_20210328_2144'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='traindata',
            table='TrainData',
        ),
    ]
