# Generated by Django 3.1.7 on 2021-07-05 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmdb', '0004_auto_20210516_2041'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroupUserMovie',
            new_name='GroupMovie',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='description_ro',
        ),
    ]
