# Generated by Django 3.1.7 on 2021-04-23 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmdb', '0005_auto_20210417_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
    ]
