# Generated by Django 3.1.7 on 2021-03-28 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmdb', '0006_auto_20210328_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traindata',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
