# Generated by Django 3.1.7 on 2021-04-27 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filmdb', '0006_user_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(db_column='group_name', max_length=100)),
            ],
            options={
                'db_table': 'Group',
            },
        ),
        migrations.CreateModel(
            name='GroupUser',
            fields=[
                ('group_user_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_id', models.ForeignKey(db_column='group_id', on_delete=django.db.models.deletion.CASCADE, to='filmdb.group')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='filmdb.user')),
            ],
            options={
                'db_table': 'GroupUser',
            },
        ),
        migrations.CreateModel(
            name='GroupUserMovie',
            fields=[
                ('group_user_movie_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_user_id', models.ForeignKey(db_column='group_user_id', on_delete=django.db.models.deletion.CASCADE, to='filmdb.groupuser')),
                ('movie_id', models.ForeignKey(db_column='movie_id', on_delete=django.db.models.deletion.CASCADE, to='filmdb.movie')),
            ],
            options={
                'db_table': 'GroupUserMovie',
            },
        ),
    ]
