# Generated by Django 3.1.7 on 2021-03-28 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmdb', '0007_auto_20210328_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='traindata',
            name='rating',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
