# Generated by Django 3.1.7 on 2021-03-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmdb', '0009_auto_20210329_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediction',
            name='rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='traindata',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
