# Generated by Django 3.1.7 on 2021-04-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmdb', '0010_auto_20210330_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image_url',
            field=models.CharField(default='url', max_length=250),
            preserve_default=False,
        ),
    ]
