# Generated by Django 3.1.7 on 2021-04-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmdb', '0011_movie_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.CharField(default='description', max_length=1000),
            preserve_default=False,
        ),
    ]
