# Generated by Django 3.1.7 on 2021-04-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmdb', '0012_movie_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='image_url',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
